version: "3"
services:
  app:
    container_name: projektaufgabe
    build: .
    image: jonthnm/projektaufgabe_mader_dogan
    ports:
      - 3000:3000 # forward webserver on 3000-http port
    depends_on:
      - mongoservice

  mongoservice:
    container_name: mongo 
    image: mongo # image retrieved from docker hub
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
  mongoexpressservice: 
    image: mongo-express # image retrieved from docker hub
    restart: always
    ports: 
      - '8081:8081'
    depends_on: 
      - mongoservice